const actionTypes = {
  GET_HOME: "GET_HOME",
  SET_CUR_SONG_ID: "SET_CUR_SONG_ID",
  SET_CUR_ALBUM_ID: "SET_CUR_ALBUM_ID",
  GET_INFO_SONG: "GET_INFO_SONG",
  GET_ALBUM: "GET_ALBUM",
  GET_SOURSE: "GET_SOURSE",
  // music
  PLAY: "PLAY",
  LOADING: "LOADING",
  RESENT_SONG: "RESENT_SONG",
  SEARCH: "SEARCH",
  SEARCH_VALUE: "SEARCH_VALUE",
};

export default actionTypes;
